<?php
namespace HB\Clementine;
class Color{
	
	const ALICEBLUE= array("aliceblue", "#F0F8FF") ;
	const ANTIQUEWHITE= array( "antiquewhite", "#FAEBD7" ) ;
	const AQUA= array( "aqua", "#00FFFF" ) ;
	const AQUAMARINE= array( "aquamarine", "#7FFFD4" ) ;
	const AZURE= array( "azure", "#F0FFFF" ) ;
	const BEIGE= array( "beige", "#F5F5DC" ) ;
	const BISQUE= array( "bisque", "#FFE4C4" ) ;
	const BLACK= array( "black", "#000000" ) ;
	const BLANCHEDALMOND= array( "blanchedalmond", "#FFEBCD" ) ;
	const BLUE= array( "blue", "#0000FF" ) ;
	const BLUEVIOLET= array( "blueviolet", "#8A2BE2" ) ;
	const BROWN= array( "brown", "#A52A2A" ) ;
	const BURLYWOOD= array( "burlywood", "#DEB887" ) ;
	const CADETBLUE= array( "cadetblue", "#5F9EA0" ) ;
	const CHARTREUSE= array( "chartreuse", "#7FFF00" ) ;
	const CHOCOLATE= array( "chocolate", "#D2691E" ) ;
	const CORAL= array( "coral", "#FF7F50" ) ;
	const CORNFLOWERBLUE= array( "cornflowerblue", "#6495ED" ) ;
	const CORNSILK= array( "cornsilk", "#FFF8DC" ) ;
	const CRIMSON= array( "crimson", "#DC143C" ) ;
	const CYAN= array( "cyan", "#00FFFF" ) ;
	const DARKBLUE= array( "darkblue", "#00008B" ) ;
	const DARKCYAN= array( "darkcyan", "#008B8B" ) ;
	const DARKGOLDENROD= array( "darkgoldenrod", "#B8860B" ) ;
	const DARKGRAY= array( "darkgray", "#A9A9A9" ) ;
	const DARKGREY= array( "darkgrey", "#A9A9A9" ) ;
	const DARKGREEN= array( "darkgreen", "#006400" ) ;
	const DARKKHAKI= array( "darkkhaki", "#BDB76B" ) ;
	const DARKMAGENTA= array( "darkmagenta", "#8B008B" ) ;
	const DARKOLIVEGREEN= array( "darkolivegreen", "#556B2F" ) ;
	const DARKORANGE= array( "darkorange", "#FF8C00" ) ;
	const DARKORCHID= array( "darkorchid", "#9932CC" ) ;
	const DARKRED= array( "darkred", "#8B0000" ) ;
	const DARKSALMON= array( "darksalmon", "#E9967A" ) ;
	const DARKSEAGREEN= array( "darkseagreen", "#8FBC8F" ) ;
	const DARKSLATEBLUE= array( "darkslateblue", "#483D8B" ) ;
	const DARKSLATEGRAY= array( "darkslategray", "#2F4F4F" ) ;
	const DARKSLATEGREY= array( "darkslategrey", "#2F4F4F" ) ;
	const DARKTURQUOISE= array( "darkturquoise", "#00CED1" ) ;
	const DARKVIOLET= array( "darkviolet", "#9400D3" ) ;
	const DEEPPINK= array( "deeppink", "#FF1493" ) ;
	const DEEPSKYBLUE= array( "deepskyblue", "#00BFFF" ) ;
	const DIMGRAY= array( "dimgray", "#696969" ) ;
	const DIMGREY= array( "dimgrey", "#696969" ) ;
	const DODGERBLUE= array( "dodgerblue", "#1E90FF" ) ;
	const FIREBRICK= array( "firebrick", "#B22222" ) ;
	const FLORALWHITE= array( "floralwhite", "#FFFAF0" ) ;
	const FORESTGREEN= array( "forestgreen", "#228B22" ) ;
	const FUCHSIA= array( "fuchsia", "#FF00FF" ) ;
	const GAINSBORO= array( "gainsboro", "#DCDCDC" ) ;
	const GHOSTWHITE= array( "ghostwhite", "#F8F8FF" ) ;
	const GOLD= array( "gold", "#FFD700" ) ;
	const GOLDENROD= array( "goldenrod", "#DAA520" ) ;
	const GRAY= array( "gray", "#808080" ) ;
	const GREY= array( "grey", "#808080" ) ;
	const GREEN= array( "green", "#008000" ) ;
	const GREENYELLOW= array( "greenyellow", "#ADFF2F" ) ;
	const HONEYDEW= array( "honeydew", "#F0FFF0" ) ;
	const HOTPINK= array( "hotpink", "#FF69B4" ) ;
	const INDIANRED= array( "indianred", "#CD5C5C" ) ;
	const INDIGO= array( "indigo", "#4B0082" ) ;
	const IVORY= array( "ivory", "#FFFFF0" ) ;
	const KHAKI= array( "khaki", "#F0E68C" ) ;
	const LAVENDER= array( "lavender", "#E6E6FA" ) ;
	const LAVENDERBLUSH= array( "lavenderblush", "#FFF0F5" ) ;
	const LAWNGREEN= array( "lawngreen", "#7CFC00" ) ;
	const LEMONCHIFFON= array( "lemonchiffon", "#FFFACD" ) ;
	const LIGHTBLUE= array( "lightblue", "#ADD8E6" ) ;
	const LIGHTCORAL= array( "lightcoral", "#F08080" ) ;
	const LIGHTCYAN= array( "lightcyan", "#E0FFFF" ) ;
	const LIGHTGOLDENRODYELLOW= array( "lightgoldenrodyellow", "#FAFAD2" ) ;
	const LIGHTGRAY= array( "lightgray", "#D3D3D3" ) ;
	const LIGHTGREY= array( "lightgrey", "#D3D3D3" ) ;
	const LIGHTGREEN= array( "lightgreen", "#90EE90" ) ;
	const LIGHTPINK= array( "lightpink", "#FFB6C1" ) ;
	const LIGHTSALMON= array( "lightsalmon", "#FFA07A" ) ;
	const LIGHTSEAGREEN= array( "lightseagreen", "#20B2AA" ) ;
	const LIGHTSKYBLUE= array( "lightskyblue", "#87CEFA" ) ;
	const LIGHTSLATEGRAY= array( "lightslategray", "#778899" ) ;
	const LIGHTSLATEGREY= array( "lightslategrey", "#778899" ) ;
	const LIGHTSTEELBLUE= array( "lightsteelblue", "#B0C4DE" ) ;
	const LIGHTYELLOW= array( "lightyellow", "#FFFFE0" ) ;
	const LIME= array( "lime", "#00FF00" ) ;
	const LIMEGREEN= array( "limegreen", "#32CD32" ) ;
	const LINEN= array( "linen", "#FAF0E6" ) ;
	const MAGENTA= array( "magenta", "#FF00FF" ) ;
	const MAROON= array( "maroon", "#800000" ) ;
	const MEDIUMAQUAMARINE= array( "mediumaquamarine", "#66CDAA" ) ;
	const MEDIUMBLUE= array( "mediumblue", "#0000CD" ) ;
	const MEDIUMORCHID= array( "mediumorchid", "#BA55D3" ) ;
	const MEDIUMPURPLE= array( "mediumpurple", "#9370DB" ) ;
	const MEDIUMSEAGREEN= array( "mediumseagreen", "#3CB371" ) ;
	const MEDIUMSLATEBLUE= array( "mediumslateblue", "#7B68EE" ) ;
	const MEDIUMSPRINGGREEN= array( "mediumspringgreen", "#00FA9A" ) ;
	const MEDIUMTURQUOISE= array( "mediumturquoise", "#48D1CC" ) ;
	const MEDIUMVIOLETRED= array( "mediumvioletred", "#C71585" ) ;
	const MIDNIGHTBLUE= array( "midnightblue", "#191970" ) ;
	const MINTCREAM= array( "mintcream", "#F5FFFA" ) ;
	const MISTYROSE= array( "mistyrose", "#FFE4E1" ) ;
	const MOCCASIN= array( "moccasin", "#FFE4B5" ) ;
	const NAVAJOWHITE= array( "navajowhite", "#FFDEAD" ) ;
	const NAVY= array( "navy", "#000080" ) ;
	const OLDLACE= array( "oldlace", "#FDF5E6" ) ;
	const OLIVE= array( "olive", "#808000" ) ;
	const OLIVEDRAB= array( "olivedrab ", "#6B8E23" ) ;
	const ORANGE= array( "orange", "#FFA500" ) ;
	const ORANGERED= array( "orangered", "#FF4500" ) ;
	const ORCHID= array( "orchid", "#DA70D6" ) ;
	const PALEGOLDENROD= array( "palegoldenrod", "#EEE8AA" ) ;
	const PALEGREEN= array( "palegreen", "#98FB98" ) ;
	const PALETURQUOISE= array( "paleturquoise", "#AFEEEE" ) ;
	const PALEVIOLETRED= array( "palevioletred", "#DB7093" ) ;
	const PAPAYAWHIP= array( "papayawhip", "#FFEFD5" ) ;
	const PEACHPUFF= array( "peachpuff", "#FFDAB9" ) ;
	const PERU= array( "peru", "#CD853F" ) ;
	const PINK= array( "pink", "#FFC0CB" ) ;
	const PLUM= array( "plum", "#DDA0DD" ) ;
	const POWDERBLUE= array( "powderblue", "#B0E0E6" ) ;
	const PURPLE= array( "purple", "#800080" ) ;
	const REBECCAPURPLE= array( "rebeccapurple", "#663399" ) ;
	const RED= array( "red", "#FF0000" ) ;
	const ROSYBROWN= array( "rosybrown", "#BC8F8F" ) ;
	const ROYALBLUE= array( "royalblue", "#4169E1" ) ;
	const SADDLEBROWN= array( "saddlebrown", "#8B4513" ) ;
	const SALMON= array( "salmon", "#FA8072" ) ;
	const SANDYBROWN= array( "sandybrown", "#F4A460" ) ;
	const SEAGREEN= array( "seagreen", "#2E8B57" ) ;
	const SEASHELL= array( "seashell", "#FFF5EE" ) ;
	const SIENNA= array( "sienna", "#A0522D" ) ;
	const SILVER= array( "silver", "#C0C0C0" ) ;
	const SKYBLUE= array( "skyblue", "#87CEEB" ) ;
	const SLATEBLUE= array( "slateblue", "#6A5ACD" ) ;
	const SLATEGRAY= array( "slategray", "#708090" ) ;
	const SLATEGREY= array( "slategrey", "#708090" ) ;
	const SNOW= array( "snow", "#FFFAFA" ) ;
	const SPRINGGREEN= array( "springgreen", "#00FF7F" ) ;
	const STEELBLUE= array( "steelblue", "#4682B4" ) ;
	const TAN= array( "tan", "#D2B48C" ) ;
	const TEAL= array( "teal", "#008080" ) ;
	const THISTLE= array( "thistle", "#D8BFD8" ) ;
	const TOMATO= array( "tomato", "#FF6347" ) ;
	const TURQUOISE= array( "turquoise", "#40E0D0" ) ;
	const VIOLET= array( "violet", "#EE82EE" ) ;
	const WHEAT= array( "wheat", "#F5DEB3" ) ;
	const WHITE= array( "white", "#FFFFFF" ) ;
	const WHITESMOKE= array( "whitesmoke", "#F5F5F5" ) ;
	const YELLOW= array( "yellow", "#FFFF00" ) ;
	const YELLOWGREEN= array( "yellowgreen", "#9ACD32" ) ;
		
	private $color;
	
	
	public function __construct($color=NULL){
		if(isset($color)){
			if(self::MatchColor($color)){
				$this->color = $color;
			}else{ 
				$this->color = NULL;
			}
		}else{
			$this->color = NULL;
		}
	}
	
	/*
	 * Check if value is in color name, rgb or HEX format
	 * @param $color
	 * @return Boolean
	 */ 
	public static function MatchColor($color){
		
		if(preg_match('/^[0-2]([0-5]{1,2})?,[0-2]([0-5]{1,2})?,[0-2]([0-5]{1,2})?(,[0-1].[0-9])?$/', $color)){ return true; }			
		if(preg_match('/^#\w+$/', $color)) $color = "#".strtoupper(substr($color, 1));
		if(preg_match('/^\w+$/', $color)) $color = strtolower($color);						
		
		if(in_array($color, self::ALICEBLUE)) return true;
		if(in_array($color, self::ANTIQUEWHITE)) return true;
		if(in_array($color, self::AQUA)) return true;
		if(in_array($color, self::AQUAMARINE)) return true;
		if(in_array($color, self::AZURE)) return true;
		if(in_array($color, self::BEIGE)) return true;
		if(in_array($color, self::BISQUE)) return true;
		if(in_array($color, self::BLACK)) return true;
		if(in_array($color, self::BLANCHEDALMOND)) return true;
		if(in_array($color, self::BLUE)) return true;
		if(in_array($color, self::BLUEVIOLET)) return true;
		if(in_array($color, self::BROWN)) return true;
		if(in_array($color, self::BURLYWOOD)) return true;
		if(in_array($color, self::CADETBLUE)) return true;
		if(in_array($color, self::CHARTREUSE)) return true;
		if(in_array($color, self::CHOCOLATE)) return true;
		if(in_array($color, self::CORAL)) return true;
		if(in_array($color, self::CORNFLOWERBLUE)) return true;
		if(in_array($color, self::CORNSILK)) return true;
		if(in_array($color, self::CRIMSON)) return true;
		if(in_array($color, self::CYAN)) return true;
		if(in_array($color, self::DARKBLUE)) return true;
		if(in_array($color, self::DARKCYAN)) return true;
		if(in_array($color, self::DARKGOLDENROD)) return true;
		if(in_array($color, self::DARKGRAY)) return true;
		if(in_array($color, self::DARKGREY)) return true;
		if(in_array($color, self::DARKGREEN)) return true;
		if(in_array($color, self::DARKKHAKI)) return true;
		if(in_array($color, self::DARKMAGENTA)) return true;
		if(in_array($color, self::DARKOLIVEGREEN)) return true;
		if(in_array($color, self::DARKORANGE)) return true;
		if(in_array($color, self::DARKORCHID)) return true;
		if(in_array($color, self::DARKRED)) return true;
		if(in_array($color, self::DARKSALMON)) return true;
		if(in_array($color, self::DARKSEAGREEN)) return true;
		if(in_array($color, self::DARKSLATEBLUE)) return true;
		if(in_array($color, self::DARKSLATEGRAY)) return true;
		if(in_array($color, self::DARKSLATEGREY)) return true;
		if(in_array($color, self::DARKTURQUOISE)) return true;
		if(in_array($color, self::DARKVIOLET)) return true;
		if(in_array($color, self::DEEPPINK)) return true;
		if(in_array($color, self::DEEPSKYBLUE)) return true;
		if(in_array($color, self::DIMGRAY)) return true;
		if(in_array($color, self::DIMGREY)) return true;
		if(in_array($color, self::DODGERBLUE)) return true;
		if(in_array($color, self::FIREBRICK)) return true;
		if(in_array($color, self::FLORALWHITE)) return true;
		if(in_array($color, self::FORESTGREEN)) return true;
		if(in_array($color, self::FUCHSIA)) return true;
		if(in_array($color, self::GAINSBORO)) return true;
		if(in_array($color, self::GHOSTWHITE)) return true;
		if(in_array($color, self::GOLD)) return true;
		if(in_array($color, self::GOLDENROD)) return true;
		if(in_array($color, self::GRAY)) return true;
		if(in_array($color, self::GREY)) return true;
		if(in_array($color, self::GREEN)) return true;
		if(in_array($color, self::GREENYELLOW)) return true;
		if(in_array($color, self::HONEYDEW)) return true;
		if(in_array($color, self::HOTPINK)) return true;
		if(in_array($color, self::INDIANRED)) return true;
		if(in_array($color, self::INDIGO)) return true;
		if(in_array($color, self::IVORY)) return true;
		if(in_array($color, self::KHAKI)) return true;
		if(in_array($color, self::LAVENDER)) return true;
		if(in_array($color, self::LAVENDERBLUSH)) return true;
		if(in_array($color, self::LAWNGREEN)) return true;
		if(in_array($color, self::LEMONCHIFFON)) return true;
		if(in_array($color, self::LIGHTBLUE)) return true;
		if(in_array($color, self::LIGHTCORAL)) return true;
		if(in_array($color, self::LIGHTCYAN)) return true;
		if(in_array($color, self::LIGHTGOLDENRODYELLOW)) return true;
		if(in_array($color, self::LIGHTGRAY)) return true;
		if(in_array($color, self::LIGHTGREY)) return true;
		if(in_array($color, self::LIGHTGREEN)) return true;
		if(in_array($color, self::LIGHTPINK)) return true;
		if(in_array($color, self::LIGHTSALMON)) return true;
		if(in_array($color, self::LIGHTSEAGREEN)) return true;
		if(in_array($color, self::LIGHTSKYBLUE)) return true;
		if(in_array($color, self::LIGHTSLATEGRAY)) return true;
		if(in_array($color, self::LIGHTSLATEGREY)) return true;
		if(in_array($color, self::LIGHTSTEELBLUE)) return true;
		if(in_array($color, self::LIGHTYELLOW)) return true;
		if(in_array($color, self::LIME)) return true;
		if(in_array($color, self::LIMEGREEN)) return true;
		if(in_array($color, self::LINEN)) return true;
		if(in_array($color, self::MAGENTA)) return true;
		if(in_array($color, self::MAROON)) return true;
		if(in_array($color, self::MEDIUMAQUAMARINE)) return true;
		if(in_array($color, self::MEDIUMBLUE)) return true;
		if(in_array($color, self::MEDIUMORCHID)) return true;
		if(in_array($color, self::MEDIUMPURPLE)) return true;
		if(in_array($color, self::MEDIUMSEAGREEN)) return true;
		if(in_array($color, self::MEDIUMSLATEBLUE)) return true;
		if(in_array($color, self::MEDIUMSPRINGGREEN)) return true;
		if(in_array($color, self::MEDIUMTURQUOISE)) return true;
		if(in_array($color, self::MEDIUMVIOLETRED)) return true;
		if(in_array($color, self::MIDNIGHTBLUE)) return true;
		if(in_array($color, self::MINTCREAM)) return true;
		if(in_array($color, self::MISTYROSE)) return true;
		if(in_array($color, self::MOCCASIN)) return true;
		if(in_array($color, self::NAVAJOWHITE)) return true;
		if(in_array($color, self::NAVY)) return true;
		if(in_array($color, self::OLDLACE)) return true;
		if(in_array($color, self::OLIVE)) return true;
		if(in_array($color, self::OLIVEDRAB)) return true;
		if(in_array($color, self::ORANGE)) return true;
		if(in_array($color, self::ORANGERED)) return true;
		if(in_array($color, self::ORCHID)) return true;
		if(in_array($color, self::PALEGOLDENROD)) return true;
		if(in_array($color, self::PALEGREEN)) return true;
		if(in_array($color, self::PALETURQUOISE)) return true;
		if(in_array($color, self::PALEVIOLETRED)) return true;
		if(in_array($color, self::PAPAYAWHIP)) return true;
		if(in_array($color, self::PEACHPUFF)) return true;
		if(in_array($color, self::PERU)) return true;
		if(in_array($color, self::PINK)) return true;
		if(in_array($color, self::PLUM)) return true;
		if(in_array($color, self::POWDERBLUE)) return true;
		if(in_array($color, self::PURPLE)) return true;
		if(in_array($color, self::REBECCAPURPLE)) return true;
		if(in_array($color, self::RED)) return true;
		if(in_array($color, self::ROSYBROWN)) return true;
		if(in_array($color, self::ROYALBLUE)) return true;
		if(in_array($color, self::SADDLEBROWN)) return true;
		if(in_array($color, self::SALMON)) return true;
		if(in_array($color, self::SANDYBROWN)) return true;
		if(in_array($color, self::SEAGREEN)) return true;
		if(in_array($color, self::SEASHELL)) return true;
		if(in_array($color, self::SIENNA)) return true;
		if(in_array($color, self::SILVER)) return true;
		if(in_array($color, self::SKYBLUE)) return true;
		if(in_array($color, self::SLATEBLUE)) return true;
		if(in_array($color, self::SLATEGRAY)) return true;
		if(in_array($color, self::SLATEGREY)) return true;
		if(in_array($color, self::SNOW)) return true;
		if(in_array($color, self::SPRINGGREEN)) return true;
		if(in_array($color, self::STEELBLUE)) return true;
		if(in_array($color, self::TAN)) return true;
		if(in_array($color, self::TEAL)) return true;
		if(in_array($color, self::THISTLE)) return true;
		if(in_array($color, self::TOMATO)) return true;
		if(in_array($color, self::TURQUOISE)) return true;
		if(in_array($color, self::VIOLET)) return true;
		if(in_array($color, self::WHEAT)) return true;
		if(in_array($color, self::WHITE)) return true;
		if(in_array($color, self::WHITESMOKE)) return true;
		if(in_array($color, self::YELLOW)) return true;
		if(in_array($color, self::YELLOWGREEN)) return true;
		return false;
	}
	
}


?>
